POST https://github.com/login/oauth/access_token
Content-Type: application/json
Accept: application/json

{
  "client_id": "{{github_client_id}}",
  "client_secret": "{{github_client_secret}}",
  "code": "{{code}}"
}

> {%
    client.test("Store access token", function () {
        client.global.set("github_token", response.body.access_token);
    });
%}
